name: build

on:
  - push
  - pull_request

jobs:
  buildit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: esphome-dlms-meter

      - name: Copy config
        run: |
          cp "./esphome-dlms-meter/meter01.example.yaml" "meter01.yaml"

      - name: Build
        uses: esphome/build-action@v1
        with:
          yaml_file: meter01.yaml
